architecture:
  version: 0.2
  subtree:
  - name: System
    local:
    - name: MainMemory
      class: DRAM
      attributes:
        width: 64
        word-bits: 8

    subtree:
    - name: PE
      local:
      - name: Buffer
        class: regfile
        attributes:
          sizeKB: 2147483648
          instances: 1
          word-bits: 8

      - name: MACC
        class: intmac
        attributes:
          datawidth: 8
