mapper:
  optimization-metrics: [ last-level-accesses, energy ]
  algorithm: linear-pruned
  victory-condition: 0
  timeout: 0
  log_orojenesis_mappings: True
  num-threads: 8
  log_mappings_yaml: False


mapspace_constraints:
  - target: Buffer
    type: temporal
    permutation: MKNGH
  - target: MainMemory
    type: temporal

  - target: Buffer
    type: datatype
    keep:
      - Weights
      - Inputs
      - Outputs
    bypass:
      []

  - target: MainMemory
    type: datatype
    keep:
      - Weights
      - Inputs
      - Outputs
    bypass:
      []


