architecture:
  version: 0.2

  subtree:
  - name: System
    local:
    - name: MainMemory
      class: DRAM
      attributes:
        width: 64
        word-bits: 16

    subtree:
    - name: PE

      local:
      - name: InputOutputBuffer
        class: regfile
        attributes:
          sizeKB: 2147483648
          instances: 1
          word-bits: 16

      - name: WeightBuffer
        class: regfile
        attributes:
          sizeKB: 2147483648
          instances: 1
          word-bits: 16

      - name: MACC
        class: intmac
        attributes:
          datawidth: 16
